name: CI

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install Dependencies
      run: npm install
    - name: Deploy
      env: 
        GH_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
      run: ng deploy --cname aqua.samnyan.icu
